parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
        types:
            identity_type: App\Doctrine\Type\IdentityType
            file_identity_type: App\Doctrine\Type\FileIdentityType
            outlet_identity_type: App\Doctrine\Type\OutletIdentityType
            commercial_network_identity_type: App\Doctrine\Type\CommercialNetworkIdentityType
            address_type: App\Doctrine\Type\AddressType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Domain:
                is_bundle: false
                type: php
                dir: '%kernel.project_dir%/db/doctrine/mappings'
                prefix: 'Domain'
