name: Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testing:

    runs-on: ubuntu-latest

    env:
      MYSQL_USER: web
      MYSQL_PASSWORD: web
      MYSQL_DATABASE: monitorings_test
      DATABASE_URL: mysql://web:web@127.0.0.1:3306/monitorings_test?serverVersion=5.7

    steps:
      - name: Run MySQL service
        run: |
          docker run -e MYSQL_DATABASE=$MYSQL_DATABASE -e MYSQL_RANDOM_ROOT_PASSWORD=1 \
            -d -p 3306:3306 mysql:5.7 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-php-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Verify database connection
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"3306" --silent; do
            sleep 1
          done

      - name: Execute migrations
        run: bin/phinx migrate

      - name: Run PHPUnit
        run: bin/phpunit --coverage-text --colors=never
